----------------------check function and trigger successfully created----------------------
SELECT trigger_name, event_object_table, event_manual_column_update,
       action_timing, action_statement
FROM information_schema.triggers
WHERE event_object_table = 'indoor_network';

SELECT proname, prosrc
FROM pg_proc
WHERE proname = 'update_shape_len';

--------------------------------------------------------------------------------------------


/* View State on Specific Date */
WITH target_date AS (
    SELECT '2024-02-10 12:00:00'::timestamp as point_in_time
)
SELECT * FROM indoor_network
WHERE created_at <= (SELECT point_in_time FROM target_date)
  -- The row has not been updated since the target date
  AND updated_at <= (SELECT point_in_time FROM target_date)

UNION ALL

SELECT 
    -- Explicitly select columns to match the main table structure if needed
    pedrouteid, displayname, inetworkid, highway, oneway, emergency, wheelchair, 
    flpolyid, crtdt, crtby, lstamddt, lstamdby, restricted, shape, feattype, 
    floorid, location, gradient, wc_access, wc_barrier, direction, bldgid_1, 
    bldgid_2, siteid, aliasnamtc, aliasnamen, terminalid, acstimeid, crossfeat, 
    st_code, st_nametc, st_nameen, modifiedby, poscertain, datasrc, levelsrc, 
    enabled, shape_len, level_id, buildnamen, buildnamzh, leveleng, levelzh, 
    mainexit, created_at, updated_at
FROM indoor_network_history
WHERE created_at <= (SELECT point_in_time FROM target_date)
  -- It was recorded in history AFTER our target date (meaning it was valid THEN)
  AND history_recorded_at > (SELECT point_in_time FROM target_date)
  -- Filter to ignore 'DELETE' entries if you only want valid lines
  AND operation = 'UPDATE';

  
------By Business ID (inetworkid), In data engineering, the "Business Key" usually describes the ID that comes from the external business source (the shapefile).
  SELECT 
    history_recorded_at as changed_at, 
    operation, 
    modifiedby as changed_by,
    shape, -- Geometry geometry
    highways -- or other attributes to compare
FROM indoor_network_history
WHERE inetworkid = 'Walkway_L1_001' -- Replace with specific ID
ORDER BY history_recorded_at DESC;


------By Database ID (pedrouteid), In data engineering, the "Surrogate Key" usually describes the internal database ID (the pedrouteid).
------Technically, it is generated by the Database engine.
  SELECT 
    history_recorded_at as changed_at, 
    operation, 
    modifiedby as changed_by,
    shape, -- Geometry geometry
    highways -- or other attributes to compare


----- fubd deleted features
SELECT * 
FROM indoor_network_history
WHERE operation = 'DELETE'
AND history_recorded_at > NOW() - INTERVAL '7 days'; -- Deleted in last week

##  SQL Query for "Time Travel" to Feb 5, 2026
WITH target_date AS (
    SELECT '2026-02-05 23:59:59+08'::timestamptz AS snapshot_time
)
SELECT 
    -- Select all columns you need
    pedrouteid, shape, feattype, floorid, updated_at
FROM pedestrian_network
WHERE updated_at <= (SELECT snapshot_time FROM target_date)

UNION ALL

-- Restore deletions and pre-update versions from history
SELECT 
    pedrouteid, shape, feattype, floorid, updated_at
FROM pedestrian_network_history h
WHERE 
    -- It was recorded in history AFTER our target date
    -- (Meaning it was changed/deleted later, so this backup is the "valid" version for Feb 5)
    h.history_recorded_at > (SELECT snapshot_time FROM target_date)
    AND 
    -- But ensure this specific historical version was actually created/updated BEFORE Feb 5
    h.updated_at <= (SELECT snapshot_time FROM target_date)
    -- Get the most recent valid version for each ID
    AND h.history_id IN (
        SELECT history_id 
        FROM (
            SELECT 
                history_id, 
                ROW_NUMBER() OVER (PARTITION BY pedrouteid ORDER BY history_recorded_at ASC) as rn
            FROM pedestrian_network_history
            WHERE history_recorded_at > (SELECT snapshot_time FROM target_date)
        ) sub
        WHERE rn = 1
    );